### ISSUE TITLE
Determine the version number of each package

### ISSUE THREAD

**Issue by YanbingHeng** [Pecnut/stokesian-dynamics#2]
Although the demo is partially implemented, unfortunately there are still some errors. For example, after numba is enabled ,when run _**python run_simulation.py**_ the system displays :
_"File "functions_generate_R2Bexact.py", line 135: 
def Bf(gamma, d, lam_index, ss, i, j, fully_2d_problem=False): 
&lt; source elided&gt; 
YBg = YB(gamma, ss, lam_index) 
return YBg * L3(d, i, j)”_
Could you please tell me the version number of each package in the _**requirements.txt**_ document? If you are willing to help, it may be more convenient for me to debug the error according to the version number you sent.

**Comment by Pecnut** [comment]
Hi @YanbingHeng: Thanks for your issue. This week I will push a new version of the software. Once that's done, could you have another go and see how you get on? I'll leave this thread open.

**Comment by Pecnut** [comment]
Hi @YanbingHeng: Could you try now please?

**Comment by YanbingHeng** [comment]
Nice! After my testing, this update has solved most of the problems, numba can be used normally, and almost all the previous problems have been solved. However, there are still two small issues that can be resolved with minimal modifications. It is unknown whether this is due to different versions of Python packages.
The first problem is that when you run the "_python run_simulate.py 6 5 1 1 ufte_" command, you get "_TypeError: unsupported operand type(s) for -: 'list' and 'list'_". This error can be modified by changing "_dimensions = random_box_top_right-random_box_bottom_left_" in the **position_setups.py** file to "_dimensions = np.array(random_box_top_right) -np.array (random_box_bottom_left)_ "to solve.
Run this command again after modification, and the program will report "_TypeError: 'float' object cannot be interpreted as an integer_". This error can be resolved by changing the "_Ua_in[:] = ([[-1, 0, 0] for i in range(num_spheres/2)]+ [[1, 0, 0] for i in range(num_spheres/2, num_spheres)])_" to "_Ua_in[:] = ([[-1, 0, 0] for i in np.arange(num_spheres / 2)]+ [[1, 0, 0] for i in np.arange(num_spheres / 2, num_spheres)])_" in the _input_setups.py_ file.
